---
#Ansible Playbook to build and run a Docker container
 
- name: Playbook to build and run Docker
  hosts: test_server
  become: true
  gather_facts: false

  tasks:
    - name: Enable EPEL Repository on CentOS 7
      yum:
        name: epel-release
        state: latest
    
    - name: install python pip
      yum:
        name: python-pip
        state: present

    - name: install docker
      yum:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: install docker from python pip
      pip:
        name: docker
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Run Docker container using php-demo-website
      docker_container:
        name: php-demo-website
        image: kaleemsony/my-php-website
        state: started
        recreate: yes
        detach: true
        ports:
          - "80:80"
      vars:
        ansible_python_interpreter: /usr/bin/python3

